import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.get("https://opensource-demo.orangehrmlive.com/")
login = driver.find_element_by_id("txtUsername")
login.send_keys("Admin")
password = driver.find_element_by_id("txtPassword")
password.send_keys("admin123")
login_btn = driver.find_element_by_id("btnLogin")
login_btn.click()
pim = driver.find_element_by_id("menu_pim_viewPimModule")
pim.click()
time.sleep(3)
AddEmployee = driver.find_element_by_id("menu_pim_addEmployee")
AddEmployee.click()
firstname = driver.find_element_by_id("firstName")
firstname.send_keys("Igor")
lastName = driver.find_element_by_id("lastName")
lastName.send_keys("Timofeev")
Save = driver.find_element_by_id("btnSave")
Save.click()
driver.quit()